version: '2'

services:
    database:
        image: mongo:3.3

    dashboard:
        build:
            context: .

        ports:
            - 3333:3333
            - 3000:3000

        environment:
            WEBSERVICE_DATABASE: mongodb://database/pa11y

        links:
            - database
